# Create conda env "conda env create -f environment.yml" followed by "conda init"
# Activate env "conda activate calendar-tracker"
# Deactivate env "conda deactivate"
# Export current conda env "conda env export --from-history > environment.yml"

name: calendar-tracker
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - fastapi
  - uvicorn
  - python-dotenv
  - psycopg2
  - pydantic_settings
  - sqlalchemy
  - pydantic
  - pip

  - pip:

